//
//  main.swift
//  SPMLicenseKit
//
//  Created by Kota Endo on 2025/04/12.
//

import Foundation
import SPMLibraryInfoReader

// MARK: - 実行コード

guard CommandLine.arguments.count >= 3 else {
    print("Usage: spm-license-generator <workspace-state-json-path> <output-file-path>")
    exit(1)
}

let workspaceStatePath = CommandLine.arguments[1]
let outputFilePath = CommandLine.arguments[2]

do {
    let libraries = try SPMLibraryInfoReader.parseWorkspaceState(at: workspaceStatePath)

    print("Found \(libraries.count) libraries")

    var generatedCode = """
    // Generated file - Do not edit
    // Generated by SPMLicenseKit

    import Foundation
    import SPMLicenseModels
    
    /// SPMライブラリのライセンス情報
    public enum SPMLicense {
        /// 全てのライブラリ情報
        public static let libraries: [LibraryInfo] = [
    """

    for library in libraries {
      let sentence = library.licenseBody?.replacingOccurrences(of: "\"", with: "\\\"").indent(by: 1)

      generatedCode += """

        LibraryInfo(
          identity: "\(library.identity)",
          name: "\(library.name)",
          repositoryURL: \(library.repositoryURL != nil ? "\"\(library.repositoryURL!)\"" : "nil"),
          licenseBody: \"\"\"
          \(sentence ?? "")
          \"\"\"
        ),
      """
    }

    generatedCode += """

        ]

        public static func libraries(matching name: String) -> [LibraryInfo] {
            let lowercasedName = name.lowercased()
          return libraries.filter { $0.name.lowercased().contains(lowercasedName) }
        }
    }
    """

    try generatedCode.write(toFile: outputFilePath, atomically: true, encoding: .utf8)
    print("Successfully generated license info to \(outputFilePath)")
} catch {
    print("Error: \(error)")
    exit(1)
}
